@baseUrl = http://localhost:3333/api
@contentType = application/json
@protocol = HTTP/1.1

### Create Comment
POST {{baseUrl}}/comments/63d89a2ac8a662656eb38790 {{protocol}}
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2Q5MDNjYWQ0OWFjZDkyMWI1MjNiOGQiLCJ1c2VyTmFtZSI6ImpvaG4gc21pdGgiLCJlbWFpbCI6InRlc3RAdXNlci5jb20iLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwiaWF0IjoxNjc1MjI1OTEyLCJleHAiOjE2NzUyMjk1MTJ9.tZO-vKa_imJI5CPpDvj09J4Du8mv0l-SC3MtrHrgeBk

{
  "advantages": "Lorem ipsum dolor sit amet, consectetuer adipiscing eli",
  "disadvantages": "Lorem ipsum dolor sit amet, consectetuer adipiscing eli",
  "text": "Lorem ipsum dolor sit amet, consectetuer adipiscing eli",
  "rating": 5,
  "product": "63d89a2ac8a662656eb38790s"
}

### Get Comments By Product
GET {{baseUrl}}/comments/63d4cac6c800c9a699b5743a {{protocol}}

### Create Comment Bad Request
POST {{baseUrl}}/comments/63d4cac6c800c9a699b5743a {{protocol}}
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2Q2MGE2ZWExMjI1ZjIxMDE5OTkyOWMiLCJ1c2VyTmFtZSI6IkpvaG4gU21pdGgiLCJlbWFpbCI6InRlc3RAZW1haWwubG9jYWwiLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwiaWF0IjoxNjc0OTcyNTI3LCJleHAiOjE2NzQ5NzYxMjd9.s12KDzEgUcEhyeCQcC3IyI48kM8sJ4Ogb0F_Edi9IQo

{
  "advantages": "Lorem ",
  "disadvantages": "Lorem ",
  "text": "L",
  "rating": 9
}
