version: '3.5'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: guitar-shop-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: guitar-shop
    ports:
      - 27017:27017
    volumes:
      - ../../mongodb:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/guitar-shop --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - mongodb

  mongodb-express:
    image: mongo-express
    restart: always
    container_name: guitar-shop-mongodb-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_URL: mongodb://root:secret@guitar-shop-mongodb:27017/
    networks:
      - mongodb

networks:
  mongodb:
    driver: bridge
