@baseUrl = http://localhost:3333/api
@contentType = application/json
@protocol = HTTP/1.1

### Create Order
POST {{baseUrl}}/orders {{protocol}}
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2Q5MDNjYWQ0OWFjZDkyMWI1MjNiOGQiLCJ1c2VyTmFtZSI6ImpvaG4gc21pdGgiLCJlbWFpbCI6InRlc3RAdXNlci5jb20iLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwiaWF0IjoxNjc1MzE1Nzc2LCJleHAiOjE2NzUzMTkzNzZ9.ZoTfrOd_UO_59gWsoBmT3i2jXDxAS9XPLCUNap_NV-I

{
  "orderList": [
    {
      "product": "63d89a2ac8a662656eb3879a",
      "quantity": 2
    },
    {
      "product": "63d89a29c8a662656eb38788",
      "quantity": 2
    }
  ]
}

### Create Order Bad Request
POST {{baseUrl}}/orders {{protocol}}
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2Q2MGE2ZWExMjI1ZjIxMDE5OTkyOWMiLCJ1c2VyTmFtZSI6IkpvaG4gU21pdGgiLCJlbWFpbCI6InRlc3RAZW1haWwubG9jYWwiLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwiaWF0IjoxNjc0OTcyNTI3LCJleHAiOjE2NzQ5NzYxMjd9.s12KDzEgUcEhyeCQcC3IyI48kM8sJ4Ogb0F_Edi9IQo

{
  "orderList": [
    {
      "product": "63d519e0cfb70f20f8055c1d",
      "quantity": 0
    },
    {
      "product": "63d519e0cfb70f20f8055c1",
      "quantity": 2
    }
  ]
}

### Get Orders
GET {{baseUrl}}/orders {{protocol}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2Q1MTllMGNmYjcwZjIwZjgwNTVjMWIiLCJ1c2VyTmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5sb2NhbCIsInJvbGUiOiLQsNC00LzQuNC90LjRgdGC0YDQsNGC0L7RgCIsImlhdCI6MTY3NDk3MzU1MywiZXhwIjoxNjc0OTc3MTUzfQ.ebZks3D1EWT_qW6rWaewOzqx6OasyE_l5qin1fEbNDA

### Get Order
GET {{baseUrl}}/orders/63d64c31cf7b574acb34fd00 {{protocol}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2Q1MTllMGNmYjcwZjIwZjgwNTVjMWIiLCJ1c2VyTmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5sb2NhbCIsInJvbGUiOiLQsNC00LzQuNC90LjRgdGC0YDQsNGC0L7RgCIsImlhdCI6MTY3NDk4ODYyNiwiZXhwIjoxNjc0OTkyMjI2fQ.rdTPtClils8nb0AMGRGYGds4gf4Lwl9WW0i6aiscpFE

### Delete Order
DELETE  {{baseUrl}}/orders/63d5e329e70e8524d3412706 {{protocol}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2Q2MGE2ZWExMjI1ZjIxMDE5OTkyOWMiLCJ1c2VyTmFtZSI6IkpvaG4gU21pdGgiLCJlbWFpbCI6InRlc3RAZW1haWwubG9jYWwiLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwiaWF0IjoxNjc0OTcyNTI3LCJleHAiOjE2NzQ5NzYxMjd9.s12KDzEgUcEhyeCQcC3IyI48kM8sJ4Ogb0F_Edi9IQo

