@baseUrl = http://localhost:3333/api
@contentType = application/json
@protocol = HTTP/1.1

### Register User
POST {{baseUrl}}/auth/register {{protocol}}
Content-Type: {{contentType}}

{
  "userName": "John Smith",
  "email": "test3@email.local",
  "password": "secret"
}

### Register User Bad request
POST {{baseUrl}}/auth/register {{protocol}}
Content-Type: {{contentType}}

{
  "userName": "",
  "email": "testemail.local",
  "password": "secre",
  "role": "admin"
}

### Login User
POST {{baseUrl}}/auth/login {{protocol}}
Content-Type: {{contentType}}

{
  "email": "test@user.com",
  "password": "secret"
}

### Login Admin
POST {{baseUrl}}/auth/login {{protocol}}
Content-Type: {{contentType}}

{
  "email": "admin@admin.local",
  "password": "admin"
}

### Login User Not Found
POST {{baseUrl}}/auth/login {{protocol}}
Content-Type: {{contentType}}

{
  "email": "test@email1.local",
  "password": "secret"
}

### Login User Password Not Valid
POST {{baseUrl}}/auth/login {{protocol}}
Content-Type: {{contentType}}

{
  "email": "test@email.local",
  "password": "secre"
}

### Check User Status
GET {{baseUrl}}/auth/check-status {{protocol}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2Q2MGE2ZWExMjI1ZjIxMDE5OTkyOWMiLCJ1c2VyTmFtZSI6IkpvaG4gU21pdGgiLCJlbWFpbCI6InRlc3RAZW1haWwubG9jYWwiLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwiaWF0IjoxNjc0OTcyMTUyLCJleHAiOjE2NzQ5NzI0NTJ9.5LUANLPQlR57QtrQULwhXAMCvP8SeadLvQmEhVNnQu4
