@baseUrl = http://localhost:3333/api
@contentType = application/json
@protocol = HTTP/1.1

### Create Product
POST {{baseUrl}}/products {{protocol}}
Content-Type: {{contentType}}

{
  "title": "Lorem ipsum dol",
  "description": "Lorem ipsum dolor sit ame",
  "guitarType": "акустика",
  "article": "Lorem",
  "stringsNumber": "4",
  "price": 135
}


### Create Product Bad Request
POST {{baseUrl}}/products {{protocol}}
Content-Type: {{contentType}}

{
  "title": "Lorem ",
  "description": "Lorem ",
  "guitarType": "бас",
  "article": "L",
  "stringsNumber": "3",
  "price": 35
}

### Upload Photo
POST {{baseUrl}}/products/63d1515e54044183b0ecb2c9/upload-photo {{protocol}}
Content-Type: multipart/form-data; boundary=Upload

--Upload
Content-Disposition: form-data; name="photo"; filename="add-item-1.png"
Content-Type: image/png

< ./markup/img/content/add-item-1.png
--Upload--
