@baseUrl = http://localhost:3333/api
@contentType = application/json
@protocol = HTTP/1.1

### Create Product
POST {{baseUrl}}/products {{protocol}}
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2Q2MGE2ZWExMjI1ZjIxMDE5OTkyOWMiLCJ1c2VyTmFtZSI6IkpvaG4gU21pdGgiLCJlbWFpbCI6InRlc3RAZW1haWwubG9jYWwiLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwiaWF0IjoxNjc0OTcyNTI3LCJleHAiOjE2NzQ5NzYxMjd9.s12KDzEgUcEhyeCQcC3IyI48kM8sJ4Ogb0F_Edi9IQo

{
  "title": "Lorem ipsum dol",
  "description": "Lorem ipsum dolor sit ame",
  "guitarType": "акустика",
  "article": "Lorem",
  "stringsNumber": "4",
  "price": 135
}


### Create Product Bad Request
POST {{baseUrl}}/products {{protocol}}
Content-Type: {{contentType}}

{
  "title": "Lorem ",
  "description": "Lorem ",
  "guitarType": "бас",
  "article": "L",
  "stringsNumber": "3",
  "price": 35
}

### Upload Photo
PATCH {{baseUrl}}/products/63d4d0a25ce884ec1634e9d7/upload-photo {{protocol}}
Content-Type: multipart/form-data; boundary=Upload
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2Q2MGE2ZWExMjI1ZjIxMDE5OTkyOWMiLCJ1c2VyTmFtZSI6IkpvaG4gU21pdGgiLCJlbWFpbCI6InRlc3RAZW1haWwubG9jYWwiLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwiaWF0IjoxNjc0OTcyNTI3LCJleHAiOjE2NzQ5NzYxMjd9.s12KDzEgUcEhyeCQcC3IyI48kM8sJ4Ogb0F_Edi9IQo

--Upload
Content-Disposition: form-data; name="photo"; filename="add-item-1.png"
Content-Type: image/png

< ./markup/img/content/add-item-1.png
--Upload--

### Get Product
GET {{baseUrl}}/products/63d4cac6c800c9a699b57438 {{protocol}}

### Get Products
GET {{baseUrl}}/products?stringsNumber=4,6&guitarType=ukulele {{protocol}}

### Get Products
GET {{baseUrl}}/products?priceRange=1000,500000 {{protocol}}

### Get Products
GET {{baseUrl}}/products?sortingOption=price&sortType=desc {{protocol}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2Q2MGE2ZWExMjI1ZjIxMDE5OTkyOWMiLCJ1c2VyTmFtZSI6IkpvaG4gU21pdGgiLCJlbWFpbCI6InRlc3RAZW1haWwubG9jYWwiLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwiaWF0IjoxNjc0OTcyNTI3LCJleHAiOjE2NzQ5NzYxMjd9.s12KDzEgUcEhyeCQcC3IyI48kM8sJ4Ogb0F_Edi9IQo

### Get Products
GET {{baseUrl}}/products?page=2&limit=2{{protocol}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2Q2MGE2ZWExMjI1ZjIxMDE5OTkyOWMiLCJ1c2VyTmFtZSI6IkpvaG4gU21pdGgiLCJlbWFpbCI6InRlc3RAZW1haWwubG9jYWwiLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwiaWF0IjoxNjc0OTcyNTI3LCJleHAiOjE2NzQ5NzYxMjd9.s12KDzEgUcEhyeCQcC3IyI48kM8sJ4Ogb0F_Edi9IQo

### Update Product
PATCH {{baseUrl}}/products/63d4cac6c800c9a699b57438 {{protocol}}
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2Q2MGE2ZWExMjI1ZjIxMDE5OTkyOWMiLCJ1c2VyTmFtZSI6IkpvaG4gU21pdGgiLCJlbWFpbCI6InRlc3RAZW1haWwubG9jYWwiLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwiaWF0IjoxNjc0OTcyNTI3LCJleHAiOjE2NzQ5NzYxMjd9.s12KDzEgUcEhyeCQcC3IyI48kM8sJ4Ogb0F_Edi9IQo

{
  "title": "Lorem ipsum dol",
  "description": "Lorem ipsum dolor sit ame",
  "guitarType": "акустика",
  "article": "Lorem",
  "stringsNumber": "4",
  "price": 135
}

### Delete Product
DELETE {{baseUrl}}/products/63d4cac6c800c9a699b57438 {{protocol}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2Q2MGE2ZWExMjI1ZjIxMDE5OTkyOWMiLCJ1c2VyTmFtZSI6IkpvaG4gU21pdGgiLCJlbWFpbCI6InRlc3RAZW1haWwubG9jYWwiLCJyb2xlIjoi0L_QvtC70YzQt9C-0LLQsNGC0LXQu9GMIiwiaWF0IjoxNjc0OTcyNTI3LCJleHAiOjE2NzQ5NzYxMjd9.s12KDzEgUcEhyeCQcC3IyI48kM8sJ4Ogb0F_Edi9IQo

